### ISSUE TITLE
failed uploading with ios 10

### ISSUE THREAD

**Issue by ajijoyo** [3lvis/Networking#140] opened 2016-10-12 03:59 UTC
hello,
when im trying upload using 
`Networking(baseURL: constans.BASE_API_URL).POST(constans.API_CREATE_QUIZ, parameters: params, parts: part)`
but i got this:
`nw_endpoint_flow_protocol_error [14.1 128.199.251.24:443 cancelled socket-flow (null)] Socket protocol sent error: [32] Broken pipe
nw_endpoint_flow_protocol_disconnected [14.1 128.199.251.24:443 cancelled socket-flow (null)] Output protocol disconnected`
i dont know what really happen ):
(im using xcode 8, device ios10 iphone 5)
but is working fine on ios9 iphone 5

**Comment by 3lvis** [comment] 2016-10-12 08:05
Hi @ajijoyo,

Sucks that is working, I can see how annoying it is when things break randomly when jumping to a new OS. Did a quick Google search and found this, maybe is revenant for you?

http://stackoverflow.com/a/38407296/717416

As you can understand as long as I can't reproduce it, I won't be able to fix it.

Is there a chance that you can share some steps to reproduce this issue?

Thanks a lot. 💐

**Comment by 3lvis** [comment] 2016-10-20 22:27
Closing for lack of more information.

**Closed by 3lvis** 2016-10-20 22:27 UTC
